Merged from bitwise-knot/deid-microservice
Alvearie/health-patterns pull request #152
Opened 2021-06-17 20:13 UTC by KathrynElrod

2021-06-17 20:17 UTC, KathrynElrod commented
Here are my notes for changes that need to be made for full integration:

- currently, the services are hardcoded to be named "ingestion-xxxx-microservice". Does this need to be changed to remove the "ingestion-" prefix so that helm can add it back automatically? (line 6 in application.properties)
- helm needs to change "deid-config-pv" persistentvolume name (in each src/kubernetes/yml) to something unique
- have we configured the ingress correctly (ie not at all - lines 8 and 11 in each application.properties)?
- change quarkus.container-image.group in both application.properties to Alvearie

2021-06-18 19:54 UTC, ibmatc requested changes
Lots of good stuff, but a lot of comments/questions.  PLEASE apply all general comments to all parts, not just the location annotated (like use of log.warn("", e) vs log.warn("" + e) ).

2021-06-18 19:54 UTC, ibmatc commented on services/deid-core/src/main/java/com/ibm/healthpatterns/deid/DeIdentifyRest.java
> +import org.eclipse.microprofile.config.inject.ConfigProperty;
I'm not familiar with this package - is this the right annotation to be using?? Or did you mean to import from a different package?

2021-06-18 19:54 UTC, ibmatc commented on services/deid-core/src/main/java/com/ibm/healthpatterns/deid/DeIdentifyRest.java
> +	String DEID_SERVICE_URL;
All Caps are typically reserved for static/constants. Probably change this to: deidServiceURL or something similar.

2021-06-18 19:54 UTC, ibmatc commented on services/deid-core/src/main/java/com/ibm/healthpatterns/deid/DeIdentifyRest.java
> +                BufferedWriter out = new BufferedWriter(new FileWriter(defaultConfig));
use "try with resources" to guarantee file is closed:

try (BufferedWriter out = new BufferedWriter(new FileWriter(defaultConfig)) {
  out.write(defaultConfigJson);
}

2021-06-18 19:54 UTC, ibmatc commented on services/deid-core/src/main/java/com/ibm/healthpatterns/deid/DeIdentifyRest.java
> +        deid = DeIdentifier.getDeIdentifier(DEID_SERVICE_URL, DEID_FHIR_SERVER_URL, DEID_FHIR_SERVER_USERNAME,
Storing the retrieved Deidentifier object as a local variable won't be thread safe.  Instead of calling "initializeDeid" change this to "getDeid" and just return it to whatever method needs it for the length of their call.

2021-06-18 19:54 UTC, ibmatc commented on services/deid-core/src/main/java/com/ibm/healthpatterns/deid/DeIdentifyRest.java
> +        if (!configFile.exists() && !configName.equals(DEID_DEFAULT_CONFIG_NAME)) {
Doesn't this mean that I can't use a non-default config if the PV is inaccessible? I thought you indicated that I could still add configs to the live pod (Map), but if the pod was cycled I'd lose those configs.

2021-06-18 19:54 UTC, ibmatc commented on services/deid-core/src/main/java/com/ibm/healthpatterns/deid/DeIdentifyRest.java
> +            initializeDeid(configString);
same comment as above - this is where I'd recommend deid = getDeid(configString) and keep "deid" scoped to this method.

2021-06-18 19:54 UTC, ibmatc commented on services/deid-core/src/main/java/com/ibm/healthpatterns/deid/DeIdentifyRest.java
> +            logger.warn("The given input stream did not contain valid JSON: "+ e);
I may have missed some similar to this, but I'd recommend log.warn(message, e) instead of log.warn(message+e.getMessage()) as it's a more complete log

2021-06-18 19:54 UTC, ibmatc commented on services/deid-core/src/main/java/com/ibm/healthpatterns/deid/DeIdentifyRest.java
> +        if (!configFile.exists()) {
Same comment - looks like no-PV means no config storage?

2021-06-18 19:54 UTC, ibmatc commented on services/deid-core/src/main/java/com/ibm/healthpatterns/deid/DeIdentifyRest.java
> +            BufferedWriter out = new BufferedWriter(new FileWriter(configFile));
try with resources

2021-06-18 19:54 UTC, ibmatc commented on services/deid-core/src/main/java/com/ibm/healthpatterns/deid/DeIdentifyRest.java
> +            logger.warn("The given input stream did not contain valid JSON: "+ e);
log(message, e)

2021-06-18 19:54 UTC, ibmatc commented on services/deid-core/src/main/java/com/ibm/healthpatterns/deid/DeIdentifyRest.java
> +        BufferedWriter out = new BufferedWriter(new FileWriter(configFile, false));
try with resources

2021-06-18 19:54 UTC, ibmatc commented on services/pom.xml
>      <modelVersion>4.0.0</modelVersion>
I think this file can go away...? common will have a build process to build its JAR, and your projects will build their own containers/output, but building the "services" folder maybe doesn't make sense now?

2021-06-18 19:54 UTC, ibmatc commented on services/terminology-service-core/README.md
> +# microservices/terminology
Change to "services"

2021-06-18 19:54 UTC, ibmatc commented on services/terminology-service-core/README.md
> +# microservices/terminology
And example "terminology" to "Terminology Services"

2021-06-18 19:54 UTC, ibmatc commented on services/terminology-service-core/README.md
> +REST API for translating FHIR objects.
I think "translating" might be mis-construed.  "REST API for applying FHIR Terminology Services to FHIR resources." is safer.

2021-06-18 19:54 UTC, ibmatc commented on services/terminology-service-core/README.md
> +./mvnw compile quarkus:dev -DPV_PATH=./ \
what is DPV_PATH?

2021-06-18 19:54 UTC, ibmatc commented on services/terminology-service-core/README.md
> +> persistent volume must have a unique name. The helm chart in `~/.../alvearie-ingestion/`
Update URL to referenced helm chart following my latest PR changes

2021-06-18 19:54 UTC, ibmatc commented on services/terminology-service-core/README.md
> +> **_NOTE_**: Currently, due to a permissions bug with PersistentVolumes, any added mappings and
I believe this was resolved? If so, remove this note.

2021-06-18 19:54 UTC, ibmatc commented on services/terminology-service-core/kubernetes.yml
> +    app.quarkus.io/vcs-url: https://github.com/bitwise-knot/health-patterns-interns.git
Update this URL to default health-patterns location

2021-06-18 19:54 UTC, ibmatc commented on services/terminology-service-core/kubernetes.yml
> +    app.kubernetes.io/name: ingestion-terminology-microservice
replace microservice with service

2021-06-18 19:54 UTC, ibmatc commented on services/terminology-service-core/kubernetes.yml
> +    kubernetes.io/ingress.class: public-iks-k8s-nginx
Does this file get re-generated by Quarkus? If not, there are a LOT of specifics that need regular updating... ingress.class, vcs-url, version, etc...

2021-06-18 19:54 UTC, ibmatc commented on services/terminology-service-core/pom.xml
> +    <artifactId>microservices</artifactId>
same comment on "microservices"->"services"

2021-06-18 19:54 UTC, ibmatc commented on services/terminology-service-core/src/main/java/com/ibm/healthpatterns/terminology/MappingStore.java
> +public class MappingStore {
Need header explaining purpose of this class

2021-06-18 19:54 UTC, ibmatc commented on services/terminology-service-core/src/main/java/com/ibm/healthpatterns/terminology/MappingStore.java
> +        structureDefinitions.put(sdUri, vsUri);
Wouldn't it be cleaner to use a BiMap and then have intentional left and right sides (know that left is SD and right is VS?).

2021-06-18 19:54 UTC, ibmatc commented on services/terminology-service-core/src/main/java/com/ibm/healthpatterns/terminology/MappingStore.java
> +        HashSet<String> output = new HashSet<>();
a BiMap would simplify this greatly

2021-06-18 19:54 UTC, ibmatc commented on services/terminology-service-core/src/main/java/com/ibm/healthpatterns/terminology/TerminologyRest.java
> +import org.eclipse.microprofile.config.inject.ConfigProperty;
Same question as Deid - is this a normal annotation? Or did you mean to pull in a different package..?

2021-06-18 19:54 UTC, ibmatc commented on services/terminology-service-core/src/main/java/com/ibm/healthpatterns/terminology/TerminologyRest.java
> +import org.jboss.logging.Logger;
why jboss logger and not java.util?

2021-06-18 19:54 UTC, ibmatc commented on services/terminology-service-core/src/main/java/com/ibm/healthpatterns/terminology/TerminologyRest.java
> +            logger.warn("Could not initialize terminology service: \""+e+"\"");
same comment about warn(message + e) vs warn(message, e)

2021-06-18 19:54 UTC, ibmatc commented on services/terminology-service-core/src/main/resources/application.properties
> +#quarkus.kubernetes.ingress.host=health-patterns-1-dcc48c44d831198cb8496b1ec68d7d12-0000.us-east.containers.appdomain.cloud36b357914d1919babc1b110277780b9d7429ed23
Remove internal URL before delivering

2021-06-18 20:00 UTC, bitwise-knot commented on services/deid-core/.mvn/wrapper/MavenWrapperDownloader.java
> +/*
Stock Quarkus code

2021-06-18 20:01 UTC, bitwise-knot commented on services/deid-core/mvnw
> +#!/bin/sh
unmodified

2021-06-18 20:02 UTC, bitwise-knot commented on services/deid-core/src/main/docker/Dockerfile.jvm
> +####
yes this is stock, I'll add those comments

2021-06-21 13:35 UTC, KathrynElrod commented on services/terminology-service-core/README.md
> +./mvnw compile quarkus:dev -DPV_PATH=./ \
That's Maven syntax for setting environment variable PV_PATH; the argument and variable name get smushed together.

2021-06-21 14:06 UTC, KathrynElrod commented on services/terminology-service-core/kubernetes.yml
> +    kubernetes.io/ingress.class: public-iks-k8s-nginx
This was an old built file for testing purposes; it's been removed.

2021-06-21 14:10 UTC, KathrynElrod commented
more helm integration notes:

- currently in each application.properties we manually annotate `quarkus.kubernetes.annotations."kubernetes.io/ingress.class"=public-iks-k8s-nginx` so that this property is correctly set for us in the generated kubernetes.yml; is this unnecessary, and helm will take care of setting this property?

2021-06-21 14:49 UTC, surajr10 commented on services/terminology-service-core/src/main/java/com/ibm/healthpatterns/terminology/TerminologyRest.java
> +import org.jboss.logging.Logger;
Quarkus has inbuilt jboss logging and so it was simple to add and no other dependencies needed to be added. Java.util would also be as easy, so would you recommend to change it?

2021-06-21 15:33 UTC, KathrynElrod commented on services/pom.xml
>      <modelVersion>4.0.0</modelVersion>
I believe this is here because `services` is the parent package of `common`, `deid`, and `terminology` -- @bitwise-knot can you confirm?

2021-06-21 18:31 UTC, ibmatc commented on services/terminology-service-core/src/main/java/com/ibm/healthpatterns/terminology/TerminologyRest.java
> +import org.jboss.logging.Logger;
If JBoss was used because of Quarkus I'm ok leaving it. I just didn't know why it would be chosen over the JVM built-in logging for what amounts to very straight-forward logging. No need to change.

2021-06-22 17:49 UTC, bitwise-knot commented on services/deid-core/src/main/java/com/ibm/healthpatterns/deid/DeIdentifyRest.java
> +        if (!configFile.exists() && !configName.equals(DEID_DEFAULT_CONFIG_NAME)) {
resolved, functions correctly without the PV

2021-06-22 18:02 UTC, surajr10 commented on services/deid-core/src/main/java/com/ibm/healthpatterns/deid/DeIdentifyRest.java
> +import org.eclipse.microprofile.config.inject.ConfigProperty;
We used this as the quarkus guides mention that quarkus uses this package/annotations to inject configuration properties.

2021-06-22 18:45 UTC, surajr10 commented on services/terminology-service-core/src/main/java/com/ibm/healthpatterns/terminology/TerminologyRest.java
> +import org.eclipse.microprofile.config.inject.ConfigProperty;
We used this as the quarkus guides mention that quarkus uses this package/annotations to inject configuration properties.

2021-06-24 19:39 UTC, ranum commented on services/deid-core/src/main/java/com/ibm/healthpatterns/deid/DeIdentifier.java
>  	 * The types for which there is masking configuration ion this {@link DeIdentifier}s masking config.
Nit: minor type in comment

2021-06-25 12:21 UTC, ibmatc reviewed
Looks good - a few more questions I'd like addressed before I approve, but very close!

2021-06-25 12:21 UTC, ibmatc commented on services/terminology-service-core/src/test/java/com/ibm/healthpatterns/terminology/TerminologyServiceTest.java
> -/*
Why was this deleted and are there new corresponding tests?

2021-06-25 12:21 UTC, ibmatc commented on services/deid-core/src/main/java/com/ibm/healthpatterns/deid/DeIdentifier.java
> +			throw new DeIdentifierException("Error invoking the de-identification REST API" + e.getMessage());
I see this marked as resolved, but the same format is still in place. Please address/comment on this.

2021-06-25 12:21 UTC, ibmatc commented on services/terminology-service-core/README.md
> +  pv.path: "<Pesistent volume mount path - default = /mnt/data/>"
Typo - Pesistent

2021-06-25 12:21 UTC, ibmatc commented on services/terminology-service-core/src/main/resources/application.properties
> +quarkus.container-image.group=alvearie
This was set to empty in the other service. Should this be blanked here?

2021-06-25 15:00 UTC, KathrynElrod commented on services/deid-core/src/main/java/com/ibm/healthpatterns/deid/DeIdentifyRest.java
> +    private void diskSetup() {
I've committed an implementation for this, but I just want to make sure that it's threadsafe since it uses a little bit of recursion (only 1 layer). Recursive call is at line 96.

2021-06-25 16:21 UTC, KathrynElrod commented on services/terminology-service-core/src/test/java/com/ibm/healthpatterns/terminology/TerminologyServiceTest.java
> -/*
Because of the changed we made to `TerminologyService`, the old tests would not pass anymore, so we removed them for this PR. We can go back in the future to add unit tests, but for now we do not have any tests.

2021-06-25 18:49 UTC, ibmatc approved these changes
LGTM

2021-06-25 19:38 UTC, merged