initial commit for fhir-trigger service
Alvearie/health-patterns pull request #166
Opened 2021-06-18 18:24 UTC by ranum

Sending the deployment yml separately (not as part of a git delivery).

2021-06-18 18:40 UTC, ibmatc requested changes
I'd like clarification on the use of rlist before approving

2021-06-18 18:40 UTC, ibmatc commented on services/fhir-trigger/README.md
> +
It would be good to document parameters here and maybe a "docker run" example of how to deploy (similar to what the kubernetes file will do via env vars)

2021-06-18 18:40 UTC, ibmatc commented on services/fhir-trigger/fhirtrigger.py
> +                #go through the history resources looking for patient, condition, procedure, observation
Not using rlist for resource types

2021-06-18 18:40 UTC, ibmatc commented on services/fhir-trigger/fhirtrigger.py
> +                            if resourcetype in ["Condition", "Observation", "Procedure"]:
Not using rlist for resource types

2021-06-18 18:40 UTC, ibmatc commented on services/fhir-trigger/fhirtrigger.py
> +                    buildandpushtokafka(pid, rlist, producer, producertopic, fhirEndpoint, fhirusername, fhirpassword)
can we pretty up this method name (build_and_push_to_kafka or buildAndPushToKafka)?

2021-06-18 18:40 UTC, ibmatc commented on services/fhir-trigger/fhirtrigger.py
> +            print("Newbundle created...", newbundle["id"])
Missing space? "New bundle"

2021-06-18 18:40 UTC, ibmatc commented on services/fhir-trigger/fhirtrigger.py
> +            if resourcetype in ['Observation','Condition','Procedure']:
didn't use rlist here either - maybe I'm missing what rlist is for?

2021-06-18 18:40 UTC, ibmatc commented on services/fhir-trigger/fhirtrigger.py
> +def buildandpushtokafka(pid, rlist, producer, producertopic, fhirEndpoint, fhirusername, fhirpassword):
if rlist is only to determine what resources to retrieve from FHIR when building the uber bundle, why pass it in? Why not just get it from env var in this method?  If rlist is used to determine what resources warrant a trigger, you're missing a few places where rlist should be used instead of hard-coded lists.

2021-06-18 19:06 UTC, ranum commented on services/fhir-trigger/README.md
> +
good point, I'll add some additional info

2021-06-18 20:41 UTC, ranum commented on services/fhir-trigger/fhirtrigger.py
> +                    buildandpushtokafka(pid, rlist, producer, producertopic, fhirEndpoint, fhirusername, fhirpassword)
fixed

2021-06-18 20:44 UTC, ranum commented on services/fhir-trigger/fhirtrigger.py
> +def buildandpushtokafka(pid, rlist, producer, producertopic, fhirEndpoint, fhirusername, fhirpassword):
Good point, rlist is there to allow the user to configure the resources that they will allow in the constructed bundle since there may be many resources that they do not care about.  So, getting it directly when needed makes sense.

2021-06-21 20:59 UTC, ibmatc approved these changes
LGTM - thanks for the updates

2021-06-22 12:33 UTC, merged