fix delay in first kafka message
Alvearie/health-patterns pull request #190
Opened 2021-07-27 19:57 UTC by ranum

This PR will add initial topic creation (if topics are included in values.yaml) as well as "prime" the topics by populating metadata so that there is no initial delay in nifi on the first message.  

First PR using new chart structure so please double check to be sure I have the parts.  alvearie/expose-kafka:0.0.3 has already been pushed to dockerhub (not being used yet as current chart uses 0.0.2)

2021-07-27 21:57 UTC, ibmatc requested changes
A couple of minor questions/comments - I'm interested in your responses before approving.

2021-07-27 21:57 UTC, ibmatc commented on services/expose-kafka/chart/values.yaml
> +inittopics: "ingest.clinical.in,patients.updated.out,patients.enriched.out,failure.topic.in"
I would recommend leaving this blank in the "generic chart", and adding these particular topics just to the health-patterns/values.yaml under expose-kafka.inittopics.

2021-07-27 21:57 UTC, ibmatc commented on services/expose-kafka/exposekafka.py
> +init_topics = initial_topics.replace(",", " ")
can initial_topics ever be "None" (aka null)? should you handle that here?

2021-07-27 21:57 UTC, ibmatc commented on services/expose-kafka/exposekafka.py
> +while True:
Do we need to timeout?

2021-07-27 21:57 UTC, ibmatc commented on services/expose-kafka/exposekafka.py
> +        new_topic_list.append(NewTopic(name=new_topic, num_partitions=1, replication_factor=1))
do we want to pass in "num_partitions" and "replication_factor" for broader support? Not sure the impact of these parameters

2021-07-28 14:45 UTC, ranum commented on services/expose-kafka/chart/values.yaml
> +inittopics: "ingest.clinical.in,patients.updated.out,patients.enriched.out,failure.topic.in"
makes sense-done

2021-07-28 14:48 UTC, ranum commented on services/expose-kafka/exposekafka.py
> +while True:
I don't think so, the only way it doesn't exit that loop is if kafka is not coming up and that would cause other problems anyway.  The kafka pod will show a problem.

2021-07-28 14:49 UTC, ranum commented on services/expose-kafka/exposekafka.py
> +        new_topic_list.append(NewTopic(name=new_topic, num_partitions=1, replication_factor=1))
Not sure what they do either, I've always seen them as 1 in all the examples.  Maybe for now it is ok and if we learn more later we can make the change.

2021-07-28 20:19 UTC, ranum commented on services/expose-kafka/exposekafka.py
> +        new_topic_list.append(NewTopic(name=new_topic, num_partitions=1, replication_factor=1))
converted them to env variables picked up in values.yaml for expose-kafka

2021-07-28 20:19 UTC, ibmatc approved these changes
LGTM

2021-07-29 13:44 UTC, ibmatc approved these changes
LGTM

2021-07-29 13:56 UTC, merged