initial commit for cql bulk export service
Alvearie/health-patterns pull request #198
Opened 2021-07-30 20:15 UTC by ranum

2021-07-30 20:35 UTC, ibmatc requested changes
Nothing major, but a few minor changes worth getting in before initial delivery.

2021-07-30 20:35 UTC, ibmatc commented on helm-charts/health-patterns/values.yaml
> +  fhirendpoint:
in general these would be nested parms:
cql-bulkexport:
  enabled: false
  ingress:
    enabled: false
    class: *ingressClass
    hostname: *hostname
  fhir:
    endpoint:
    user:
    pw:
  cohort:
    endpoint:
  cos:
    endpoint:
    apikey:
    instancecrn:
  bucketname:
  resourcelist:

2021-07-30 20:35 UTC, ibmatc commented on services/cql-bulkexport/bulkextract.py
> +@app.route("/healthcheck", methods=['GET'])
Nit: We need to be careful about "healthcheck" vs "healthCheck" vs "health" for all of the various places we add health checks... The inconsistency is concerning. Not sure what the "right" endpoint should be though

2021-07-30 20:35 UTC, ibmatc commented on services/cql-bulkexport/chart/README.md
> +`fhirendpoint`: Set the endpoint for the FHIR server api
Update to nested parm format:
fhir.endpoint
fhir.user
etc...

2021-07-30 20:35 UTC, ibmatc commented on services/cql-bulkexport/chart/templates/_helpers.tpl
> +{{/*
I think this (bootstrap) can go away. It doesn't apply to this service.

2021-07-30 20:35 UTC, ibmatc commented on services/cql-bulkexport/chart/values.yaml
> +fhirendpoint: http://ingestion-fhir/fhir-server/api/v4
Update with nested parms

2021-07-30 20:35 UTC, ibmatc commented on services/cql-bulkexport/bulkextract.py
> +            raise Exception("ERROR-bulk export did not complete properly")
Probably should log the response code/message when this happens so we have a chance to triage what failed.

2021-07-30 20:35 UTC, ibmatc commented on services/cql-bulkexport/bulkextract.py
> +@app.route("/cql_libraries", methods=["GET"])
Is this of value?  Isn't it really just a re-direct to the cohort-service call? Not sure we want to duplicate that function...

2021-07-30 21:12 UTC, ranum commented on helm-charts/health-patterns/values.yaml
> +  fhirendpoint:
nice-done

2021-07-30 21:18 UTC, ranum commented on services/cql-bulkexport/bulkextract.py
> +@app.route("/healthcheck", methods=['GET'])
I just included it as a sanity check that the server is up and the routing/ingress works.  Could probably get rid of it, nice to have during early dev. Agree about the name.

2021-07-30 21:18 UTC, ranum commented on services/cql-bulkexport/chart/templates/_helpers.tpl
> +{{/*
done

2021-08-02 01:16 UTC, ranum commented on services/cql-bulkexport/bulkextract.py
> +            raise Exception("ERROR-bulk export did not complete properly")
Agree-done

2021-08-02 01:21 UTC, ranum commented on services/cql-bulkexport/bulkextract.py
> +@app.route("/cql_libraries", methods=["GET"])
Yes, just calling off to cohort-service here. Thought it might be nice to have it as a convenience endpoint for this service but certainly any update/add/delete of cql libraries needs to be done from the cohort-service.

2021-08-02 15:30 UTC, ibmatc approved these changes
LGTM - one nit I wish I would have caught last time.

2021-08-02 15:30 UTC, ibmatc commented on helm-charts/health-patterns/values.yaml
> +    pw:
nit: "pw" is unnecessarily short/cryptic... I would prefer "password" in general.

2021-08-02 15:45 UTC, ranum commented on helm-charts/health-patterns/values.yaml
> +    pw:
fixed

2021-08-02 15:47 UTC, merged