Cdp nlp service
Alvearie/health-patterns pull request #199
Opened 2021-07-30 21:21 UTC by surajr10

2021-08-02 15:25 UTC, ibmatc requested changes
Mostly great stuff.  A few comments needing addressing before I can approve, but a lot of little nits.  Let me know if you have any questions in my comments.

2021-08-02 15:25 UTC, ibmatc commented on services/nlp-insights/text_analytics/utils/fhir_object_utils.py
> +    if nlp_name == 'ACDService':
pass this in or call nlp.get_process_type_extension() to return the proper value.

2021-08-02 15:25 UTC, ibmatc commented on services/nlp-insights/text_analytics/utils/fhir_object_utils.py
> +    if nlp_name == 'ACDService':
same abstraction comment

2021-08-02 15:25 UTC, ibmatc commented on services/nlp-insights/text_analytics/utils/fhir_object_utils.py
> +            if nlp_name == 'ACDService':
Same abstraction comment...

2021-08-02 15:25 UTC, ibmatc commented on services/nlp-insights/text_analytics/utils/fhir_object_utils.py
> +'''
Looks like an errant, obsolete comment?

2021-08-02 15:25 UTC, ibmatc commented on services/nlp-insights/text_analytics/utils/fhir_object_utils.py
> +    confidence = create_confidence(insight_constants.CONFIDENCE_SCORE_EXPLICIT,
Do we need to check for existence of each entry:
if insight_model_data['diagnosis'] is not None:
if insight_model_data['diagnosis']['usage'] is not None:
foo(insight_model_data['diagnosis']['usage']['explicitScore'])

2021-08-02 15:25 UTC, ibmatc commented on services/nlp-insights/text_analytics/utils/fhir_object_utils.py
> +Returns the attached document as a string, decoded.
Errant/Obsolete message?

2021-08-02 15:53 UTC, bitwise-knot commented on services/nlp-insights/text_analytics/utils/fhir_object_utils.py
> +Returns the attached document as a string, decoded.
Not sure what you mean.  I think the comment describes the function that follows it fairly well.

2021-08-02 16:03 UTC, ranum commented on services/nlp-insights/README.md
> +<!-- //TODO fill in overview of how resource is augmented -->
Is this for future reminder when we add additional resource? Maybe just a comment??

2021-08-02 16:09 UTC, ranum commented on services/nlp-insights/build.gradle
> +task cdpTextAnalyticsPySetupBuild(type: PythonTask) {
If we comment out dependencies I think it would be helpful to see a more detailed description of why/when we want to use them.

2021-08-02 16:12 UTC, ranum commented on services/nlp-insights/build.gradle
> +project.tasks.cdpTextAnalyticsPyTestPrep.dependsOn project.tasks.cdpTextAnalyticsPySetupBuildProperties
Same here, it's confusing when I see commented out code/config without reason

2021-08-02 16:18 UTC, ibmatc commented on services/nlp-insights/text_analytics/utils/fhir_object_utils.py
> +Returns the attached document as a string, decoded.
Oh, is this a comment for the function below it? It looked like it was floating between methods and left behind. Nvm.

2021-08-02 16:18 UTC, bitwise-knot commented on services/nlp-insights/README.md
> +<!-- //TODO fill in overview of how resource is augmented -->
That comment is a placeholder for a small table outlining how each supported resource is augmented or what new resources are created.  I'll take care of that now.

2021-08-02 16:24 UTC, ranum commented on services/nlp-insights/text_analytics/acd/acd_service.py
> +            # print("RAW ACD Response: ", resp, "<end>")
log? remove?

2021-08-02 16:31 UTC, ranum commented on services/nlp-insights/text_analytics/acd/acd_service.py
> +        print("key:", self.acd_key)
Rogue prints?  maybe log if really want to track

2021-08-02 16:33 UTC, ranum commented on services/nlp-insights/text_analytics/acd/acd_service.py
> +    @staticmethod
Wondering about the rationale for having these be static methods of this class.  Are they utility? Is there a utility class?

2021-08-02 16:34 UTC, bitwise-knot commented on services/nlp-insights/text_analytics/utils/fhir_object_utils.py
> +'''
Same as other comment, pertains to the following function

2021-08-02 16:38 UTC, bitwise-knot commented on services/nlp-insights/text_analytics/acd/acd_service.py
> +    @staticmethod
These are utility, but they are specific to the nlp.  basically they are expected to convert each nlp's concept to a consistent dictionary that can be handled the same regardless of source.  These could be pulled out and into nlp-specific util files, but I think they make sense living inside of the nlp-specific service class.

2021-08-02 16:38 UTC, bitwise-knot commented on services/nlp-insights/text_analytics/acd/acd_service.py
> +    @staticmethod
same with the symptom function

2021-08-02 16:43 UTC, bitwise-knot commented on services/nlp-insights/text_analytics/acd/acd_service.py
> +    @staticmethod
I'll add a generic parent nlp-service class so this makes more sense and extends to other NLP services more easily

2021-08-02 16:53 UTC, ranum commented on services/nlp-insights/README.md
> +| Set up NLP with specified config | `POST` | `/setup/{configName}` | | | Status `200` |
This seems clunky to me.  What if you included your "set up" in the /config using a request parm with the configname, so PUT to    .../config?name=blah  to change the current configuration

2021-08-02 16:56 UTC, ranum commented on services/nlp-insights/text_analytics/quickUMLS/semtype_lookup.py
> +semTypes = {"T116": "umls.AminoAcidPeptideOrProtein",
Does this come from a UMLS artifact (file) that could be loaded?

2021-08-02 16:59 UTC, ranum requested changes
Some initial comments, sorry if I duplicated some of ATCs by accident.

2021-08-02 17:18 UTC, bitwise-knot commented on services/nlp-insights/text_analytics/quickUMLS/semtype_lookup.py
> +semTypes = {"T116": "umls.AminoAcidPeptideOrProtein",
https://metamap.nlm.nih.gov/SemanticTypesAndGroups.shtml

2021-08-02 17:20 UTC, bitwise-knot commented on services/nlp-insights/text_analytics/quickUMLS/semtype_lookup.py
> +semTypes = {"T116": "umls.AminoAcidPeptideOrProtein",
This is the source I pulled the umls types from. The 'semantic types mapping' file is what i used. I tried to find some way of pulling these from a maintained source, but was not finding anything promising.

2021-08-02 17:29 UTC, bitwise-knot commented on services/nlp-insights/text_analytics/acd/acd_service.py
> +    @staticmethod
Added parent class.  See if that makes more sense

2021-08-02 17:34 UTC, ibmatc commented on services/nlp-insights/text_analytics/abstract_nlp_service.py
> +from abc import ABC, abstractmethod
??

2021-08-02 18:14 UTC, ranum commented on services/nlp-insights/text_analytics/abstract_nlp_service.py
> +from abc import ABC, abstractmethod
Using abstract base class here might be overkill unless you plan to use the subclass names  to solve the tagging problem that Adam was referring to (type(obj).__name__)

2021-08-02 19:30 UTC, bitwise-knot commented on services/nlp-insights/text_analytics/abstract_nlp_service.py
> +from abc import ABC, abstractmethod
We want all of the nlp services to have the functions process, concept_to_dict, and symptom_to_dict, right?  is there a better way to do this than an abstract class?

2021-08-02 20:35 UTC, ibmatc commented on services/nlp-insights/text_analytics/abstract_nlp_service.py
> +from abc import ABC, abstractmethod
Sorry - my comment was intended to be about the import... "from abc import ABC"?

I'm ok with abstract classes in general, but we may need to discuss some of the abstraction/generalization comments if they're not clear. Once you get through the comments let me know and we can meet/discuss.

2021-08-02 20:43 UTC, bitwise-knot commented on services/nlp-insights/text_analytics/abstract_nlp_service.py
> +from abc import ABC, abstractmethod
abc is python's version of abstraction - stands for abstract base class i believe.

2021-08-03 14:57 UTC, surajr10 commented on services/nlp-insights/text_analytics/app.py
> +            jsonFile = open(configDir + f'/{configName}', 'x')
We want an error to be brought up if the file already exists, which calling the open file with 'x' does (only main difference between it and 'w'), since the request is a POST and not PUT.

2021-08-03 15:40 UTC, bitwise-knot commented on services/nlp-insights/text_analytics/acd/acd_service.py
> +        print("key:", self.acd_key)
added for debug, now removed

2021-08-03 15:41 UTC, bitwise-knot commented on services/nlp-insights/text_analytics/app.py
> +logger = logging.getLogger()
Done

2021-08-03 15:43 UTC, bitwise-knot commented on services/nlp-insights/text_analytics/app.py
> +            jsonFile = open(configDir + f'/{configName}', 'x')
in this context x isn't execute, its create

2021-08-04 07:36 UTC, surajr10 commented on services/nlp-insights/text_analytics/enhance/enhance_allergy_intolerance_payload.py
> +            text = 'Allergy to ' + allergy_intolerance_fhir.code.text
I believe it is needed for both as without the "Allergy to " text prepended to the fhir.code.text, both NLPs wouldn't understand that the text is referring to an allergy and would rather just register the drug/food/whatever is listed in the text.

2021-08-04 07:39 UTC, surajr10 commented on services/nlp-insights/text_analytics/utils/fhir_object_utils.py
> +        # TODO: Figure out how to create BundleEntryRequest not using json
Extraneous comment copied from CDP team code and is deleted.

2021-08-04 07:54 UTC, surajr10 commented on services/nlp-insights/text_analytics/insights/text_adjustments.py
> +def adjust_vaccine_text(text):
Same thing with "Allergy" hint, both NLP services would need this text added as it allows the NLP to more clearly understand the context of the text. In this case without the "vaccine" hint, the NLP services would simply register a disease and not the actual vaccine.

2021-08-04 20:50 UTC, ibmatc reviewed
LGTM - A few changes requested, but leaving it as "Comment" so I don't block you if David approves while I'm on vacation.

2021-08-04 20:50 UTC, ibmatc commented on services/nlp-insights/Dockerfile
> +# syntax=docker/dockerfile:1
Is this file valid any more, or is all supported Docker building done via the gradle config? It doesn't appear to be current.

2021-08-04 20:50 UTC, ibmatc commented on services/nlp-insights/text_analytics/enhance/enhance_allergy_intolerance_payload.py
> +            text = 'Allergy to ' + allergy_intolerance_fhir.code.text
I see.  I suppose it's a necessary evil.

2021-08-04 20:50 UTC, ibmatc commented on services/nlp-insights/text_analytics/quickUMLS/quickumls_config.ini
> +QUICKUMLS_URL=https://quickumls.wh-health-patterns.dev.watson-health.ibm.com/match
Should not deliver this value. May need some documentation/explanation of the expected service already deployed and available at a known URL, that can then be referenced here.

2021-08-04 20:50 UTC, ibmatc commented on services/nlp-insights/text_analytics/utils/fhir_object_utils.py
> +def create_coding_with_display(system, code, display=None):
the name should just be "create_coding"

2021-08-04 20:52 UTC, bitwise-knot commented on services/nlp-insights/Dockerfile
> +# syntax=docker/dockerfile:1
Good point, this is replaced by the gradle plugins.  deleting it

2021-08-04 20:57 UTC, bitwise-knot commented on services/nlp-insights/text_analytics/quickUMLS/quickumls_config.ini
> +QUICKUMLS_URL=https://quickumls.wh-health-patterns.dev.watson-health.ibm.com/match
should we reference the image used to deploy the quickumls service in the readme?

2021-08-04 21:10 UTC, ibmatc commented
One general comment - I'm not sure why the structure for this work is

health-patterns/services/nlp-insights/text-analytics/*
vs
health-patterns/services/nlp-insights/*

I don't see the value of the additional sub-folder for "text-analytics".  I think it could have been removed, but likely isn't worth it at this point (delay vs delivery)

2021-08-04 21:10 UTC, ibmatc reviewed
LGTM - only a few additional comments.

Second review looking at entire PR, not just delta since first review.

2021-08-04 21:10 UTC, ibmatc commented on services/nlp-insights/text_analytics/quickUMLS/quickumls_config.ini
> +QUICKUMLS_URL=https://quickumls.wh-health-patterns.dev.watson-health.ibm.com/match
Probably, yeah. @ranum thoughts?

2021-08-04 21:10 UTC, ibmatc commented on services/nlp-insights/text_analytics/enhance/enhance_allergy_intolerance_payload.py
> +            text = 'Allergy to ' + allergy_intolerance_fhir.code.text
Should this adjustment be moved to the text_adjustments module, to keep these adjustments in one place?

2021-08-04 21:15 UTC, ibmatc reviewed
LGTM (trying to wipe out "requested changes" flag)

2021-08-04 21:16 UTC, ibmatc reviewed
LGTM - Trying to override Requested Changes

2021-08-04 21:18 UTC, ibmatc approved these changes
LGTM - Trying to override "Requested Changes"

2021-08-04 21:40 UTC, bitwise-knot commented on services/nlp-insights/kubernetes.yml
> +apiVersion: apps/v1
Its up to you - it allows for deployment outside of the helm chart and might make things easier than going through helm to develop/debug in the future, but I've not used helm myself so I can't say.  If you don't think it will be used past initial development, then its better to get rid of it.

2021-08-04 21:41 UTC, bitwise-knot commented on services/nlp-insights/kubernetes.yml
> +apiVersion: apps/v1
Also, some acknowledgement of the helm chart should probably end up in the README, right?

2021-08-04 22:01 UTC, ibmatc commented on services/nlp-insights/kubernetes.yml
> +apiVersion: apps/v1
I think we should remove it. It's redundant and using helm doesn't lock in any other requirements or services, so it still provides a "simple" way to deploy.

The chart folder does have a README, but adding some reference linking to the chart README would be good, yes.

2021-08-05 15:31 UTC, ranum commented on services/nlp-insights/text_analytics/acd/acd_service.py
> +                    code = 'AM'
nit:  just a thought, would it be more general to say "AM" in frequency or "PM" in frequency?  Should there be a default if neither (not sure what that would be)

2021-08-05 15:40 UTC, ranum commented on services/nlp-insights/text_analytics/quickUMLS/quickumls_config.ini
> +QUICKUMLS_URL=https://quickumls.wh-health-patterns.dev.watson-health.ibm.com/match
agree

2021-08-05 16:19 UTC, ranum approved these changes
Left a few minor comments.  With Adam's primary approval already done, I am approving so this should be good to go.  Nice!

2021-08-09 16:57 UTC, merged