Disablemonitoring
Alvearie/health-patterns pull request #36
Opened 2021-01-12 18:35 UTC by ranum

After our investigation we have decided to disable the monitoring solution by default and allow users to enable it if they wish.  This PR sets the proper enabled flags to false and provides documentation as to the necessary changes that need to be made to enable in the future.

2021-01-12 20:24 UTC, ewill00 approved these changes
LGTM

2021-01-12 20:44 UTC, luisgarcc requested changes
Hi David, the changes look good, but can you rebase on top of the latest CI changes to make sure the changes will work? 
Also, a nit. The PR name should be something more meaningful than the name of the branch. Thanks!

2021-01-12 22:44 UTC, ibmatc approved these changes

2021-01-12 22:44 UTC, ibmatc commented on clinical-ingestion/helm-charts/alvearie-ingestion/README.md
> +Deletion of charts doesn't cascade to deleting associated `PersistedVolume`s and `PersistedVolumeClains`s.
typo - "PersistedVolumeClaims" m/n

2021-01-13 03:19 UTC, luisgarcc approved these changes
Thanks!

2021-01-13 14:22 UTC, merged