Automate putting Clinical Ingestion main process group on NiFi Canvas
Alvearie/health-patterns pull request #85
Opened 2021-02-16 16:49 UTC by luisgarcc

This commit changes the NiFi post init logic as follows:

- Renamed `scriptex.sh` to `initialize-reporting-task.sh`
- Containerized all the scripts. This makes it easier to add more
scripts for other purposes, it avoids downloading the reporting task
script every time NiFi starts, and it reduces the complexity where some
scripts were in the values.yaml and some had to be downloaded
- Remove volumeMount for scripts, since they are now in the new
container image
- Add the `setupClinicalIngestion.py` script, that loads the Clinical
Ingestion NiFi flow on the canvas, to the automation of the NiFi setup
such that the flow will be loaded automatically upon installation of the
chart
- Move _wait for NiFi logic_ from the `values.yaml` into its own `.sh`
file and made it configurable to any nifi:port combination
- Reduce setup scripts' verbosity not showing every JSON response which
made following the setup steps difficult, and added sleeps
- Add better error handling to the `setupClinicalIngestionFlow` such
that if it fails the pod will fail
- Better documentation in the /utilities README to include the other
scripts and also how to build the new `nifi-setup`container

2021-02-16 18:23 UTC, ibmatc approved these changes
LGTM

2021-02-16 18:23 UTC, ibmatc commented on clinical-ingestion/utilities/initialize-reporting-task.sh
> -echo $response
do we not want to print out the response any more?

2021-02-16 18:23 UTC, ibmatc commented on clinical-ingestion/helm-charts/alvearie-ingestion/values.yaml
> +          python /scripts/setupClinicalIngestionFlow.py http://$HOSTNAME:8080/ integrati0n
shouldn't this be parameterized to pass in a password from the values.yaml that can then be overridden?

2021-02-16 20:42 UTC, ranum approved these changes
Really nice work here to clean up and enhance what we had.  Much better!  Just one thought that might be stupid but, would there ever be a situation where we would not want the setup script to run? Just deploy clean?

2021-02-16 23:11 UTC, luisgarcc commented on clinical-ingestion/utilities/initialize-reporting-task.sh
> -echo $response
I don't think they were very useful (maybe for dev) and they were very big thus polluted the logs. If it turns out we can't live without them we can add them back. But I think the logs we get like this are much more helpful

2021-02-16 23:16 UTC, luisgarcc commented on clinical-ingestion/helm-charts/alvearie-ingestion/values.yaml
> +          python /scripts/setupClinicalIngestionFlow.py http://$HOSTNAME:8080/ integrati0n
I don't think the FHIR password is currently parameterezed at all in `values.yaml`.
But this PR was meant to eliminate the manual step, which required to pass in that same hard coded password.
This will have to obviously improve once we implement security.

2021-02-16 23:17 UTC, luisgarcc commented
> 
> 
> Really nice work here to clean up and enhance what we had. Much better! Just one thought that might be stupid but, would there ever be a situation where we would not want the setup script to run? Just deploy clean?

I don't think we have that requirement right now, but we could add it if needed.

2021-02-17 03:11 UTC, ibmatc requested changes
Wait to deliver until Monday afternoon

2021-02-22 17:13 UTC, ibmatc approved these changes

2021-02-22 18:29 UTC, merged