Expose Clinical Ingestion flow via Ingress
Alvearie/health-patterns pull request #87
Opened 2021-02-17 23:18 UTC by ibmatc

This will switch all use of LoadBalancers as the default way to expose services over to using Ingresses.

2021-02-18 15:02 UTC, rguderian approved these changes
Nice to see the loadbalancers go away.

2021-02-19 16:42 UTC, luisgarcc requested changes
I think there are some issues that we need to resolve on this one. My major concern is that the changes here make it so that our chart is not accessible to consumers by default and if they enabled ingress access it would be accessible but I am not sure it would work on other clouds that we have tested already.

2021-02-19 16:42 UTC, luisgarcc commented on clinical-ingestion/helm-charts/alvearie-ingestion/README.md
> +helm install ingestion . --set global.ingress.enabled=true,global.ingress.subdomain=<<INGRESS_SUBDOMAIN>>
I think installing with the ingresses should be a separate section because we know that installing with LBs works everywhere (in all clouds) and does not require any setup pre-req cloud specific commands (like `ibmcloud ks` here).

So I think you should move the `Identify ingress subdomain` section as a subsection of `Install the Chart` and this main section would leave the initial command with no parameters, then the new subsection would be called something line `Installing the Chart with Ingress access on the IBM Cloud` and there you would put the `ibmcloud ks` command the the `helm install` with parameters.

2021-02-19 16:42 UTC, luisgarcc commented on clinical-ingestion/helm-charts/alvearie-ingestion/charts/cohort-service/values.yaml
> +  type: ClusterIP
The cohort-service is majorly still a standalone app and for the reasons discussed Wednesday re: not having individual ingresses for each subchart, it makes sense that its default service type is `LoadBalancer`, you can then change that default service type on the main Chart to `ClusterIP` since the Main Chart would have a corresponding `Ingress` for it so the LB is not needed at that point

2021-02-19 16:42 UTC, luisgarcc commented on clinical-ingestion/helm-charts/alvearie-ingestion/templates/NOTES.txt
> -It may take a few minutes for the LoadBalancer IPs to be available.
What if a user wants to deploy with LBs or ClusterIPs like Rashita recently? 

I think completely getting rid of everything that is not `Ingress` is not a good idea especially because we don't know the cluster configs where ppl are running this (re: the research cluster) though I agree we should favor ingresses.

You said you had seen the NiFi chart, notice how the ingress is an optional enhancement there you can enable/disable it with a values.yaml property and it's off by default.

2021-02-19 16:42 UTC, luisgarcc commented on clinical-ingestion/helm-charts/alvearie-ingestion/templates/cohort_ingress.yaml
> +{{- if .Values.global.ingress.enabled -}}
I think you should get rid of the `global` qualifier here, anything that you put on the "root" of the yaml structure is inherently global. Notice how the nifi chart doesn't have `global.ingress.enabled` they just have `ingress.enabled`

2021-02-19 16:42 UTC, luisgarcc commented on clinical-ingestion/helm-charts/alvearie-ingestion/templates/cohort_ingress.yaml
> +{{- if index .Values "cohort-service" "enabled" -}}
A nit on the file name, the convention is to use dash-separated names, not underscore_separated, and speaking of names I am wondering if you should prefix all the services with ingres-X.yaml (instead of X-ingress.yaml) so that all ingress files are grouped together and we can more easily see them

2021-02-19 16:42 UTC, luisgarcc commented on clinical-ingestion/helm-charts/alvearie-ingestion/templates/cohort_ingress.yaml
> +    kubernetes.io/ingress.class: public-iks-k8s-nginx
Did you find out if this was an IBM Cloud specific class? If so can you add a comment and maybe a TODO or something to find out the others major ones?

2021-02-19 16:42 UTC, luisgarcc commented on clinical-ingestion/helm-charts/alvearie-ingestion/templates/deid_ingress.yaml
> +apiVersion: extensions/v1beta1
Does our version of K8s support the released apiVersion in the k8s docs?

2021-02-19 16:42 UTC, luisgarcc commented on clinical-ingestion/helm-charts/alvearie-ingestion/templates/deid_ingress.yaml
> +    ingress.kubernetes.io/proxy-read-timeout: '90'
Do we really need this timeout property? What is it for?

2021-02-19 16:42 UTC, luisgarcc commented on clinical-ingestion/helm-charts/alvearie-ingestion/templates/nifi_ingress.yaml
> +{{- $ingressPort := 8080 -}}
I think you should add a values.yaml entry in our main chart that matches the nifi's chart value for the port, and set it to 8080 there  (which is already the default) but just so that we can set the port here like you set the port for the nifi-registry. I think we should avoid having ports dangling like this within the {{ }} section of the yamls.

2021-02-19 16:42 UTC, luisgarcc commented on clinical-ingestion/helm-charts/alvearie-ingestion/templates/nifi_ingress_rest.yaml
> +{{- $ingressPort := 7001 -}}
The comment above about not having ports defined in the {{ }} section of the yamls like this, makes me wonder whether we should have exposed the port from the nifi HTTP API (7001) as a property too, maybe a future enhancement for that one.

2021-02-19 16:42 UTC, luisgarcc commented on clinical-ingestion/helm-charts/alvearie-ingestion/values.yaml
> +global:
Please see comment above on `global`

2021-02-19 16:42 UTC, luisgarcc commented on clinical-ingestion/helm-charts/alvearie-ingestion/values.yaml
> -    type: LoadBalancer
Removing the LBs from the default implementation and setting the `ingress.enabled: false` by default effectively makes it so that ppl can't access anything out of the box, and we know that some clusters may not allow port forwarding. 

I think we should leave the LBs on by default so that we know that we will still be able to deploy push-button to any of the Clouds we've tested so far. And we can include another values.yaml that we use internally and that people who are using ingresses on their IBM Cloud can use where you change these defaults, something like ibm-cloud.yaml or something. But notice again going back to what others typically do, the nifi chart does this it enables the service with LBs by default even though they do provide support for ingresses, I say do it like that too

2021-02-19 21:52 UTC, ibmatc commented on clinical-ingestion/helm-charts/alvearie-ingestion/templates/deid_ingress.yaml
> +    ingress.kubernetes.io/proxy-read-timeout: '90'
It was a property in the sample ingress given to me by Jessmon. It controls how long it will wait on the upstream server before timing out.  I'm not sure it's strictly required, but I think it's good practice to leave.

2021-02-19 21:54 UTC, ibmatc commented on clinical-ingestion/helm-charts/alvearie-ingestion/templates/cohort_ingress.yaml
> +{{- if index .Values "cohort-service" "enabled" -}}
Sure - updated.

2021-02-19 22:00 UTC, ibmatc commented on clinical-ingestion/helm-charts/alvearie-ingestion/templates/nifi_ingress.yaml
> +{{- $ingressPort := 8080 -}}
Redefining values that already exist is ugly and frustrating. Since the sub-chart will already be getting the value from the "default" values I didn't really want to re-define the value in another parameter in the base chart.  But for the sake of consolidating variable locations I've updated per your suggestion.

2021-02-19 22:01 UTC, ibmatc commented on clinical-ingestion/helm-charts/alvearie-ingestion/templates/nifi_ingress_rest.yaml
> +{{- $ingressPort := 7001 -}}
Agreed - could expose as Parameter Context parameter.  Not critical since REST api is kind of a "backdoor" more than an expected primary access point, but future enhancement opportunity

Updated this one to pull from values.yaml too.

2021-02-19 22:05 UTC, ibmatc commented on clinical-ingestion/helm-charts/alvearie-ingestion/templates/cohort_ingress.yaml
> +{{- if .Values.global.ingress.enabled -}}
I used the convention recommended here: https://helm.sh/docs/chart_template_guide/subcharts_and_globals/

This uses "global" as a keyword, but implies it is also required for other subcharts to access them. In this case (now) it's not subcharts accessing it, but I think keeping the global keyword is important/correct.

2021-02-19 22:05 UTC, ibmatc commented on clinical-ingestion/helm-charts/alvearie-ingestion/values.yaml
> +global:
same response. Keeping per helm documentation

2021-02-22 17:28 UTC, ibmatc commented on clinical-ingestion/helm-charts/alvearie-ingestion/charts/cohort-service/values.yaml
> +  type: ClusterIP
Reverted.

2021-02-22 17:30 UTC, ibmatc commented on clinical-ingestion/helm-charts/alvearie-ingestion/templates/NOTES.txt
> -It may take a few minutes for the LoadBalancer IPs to be available.
As mentioned in our meeting, I believe load balancers are the wrong approach and should be avoided when possible.  My intention was to disable them in our reference design, but obviously someone could edit our design to use them if they wanted to.  Having said that, I've discovered that the current ingress solution doesn't work out-of-the-box on Azure (at least) and will require some additional investigation to resolve.  For that reason (at least) I will be reverting the changes to omit LB's and leave them as the default, with Ingress being an enableable (and recommended) solution when possible.

2021-02-22 19:55 UTC, ibmatc commented on clinical-ingestion/helm-charts/alvearie-ingestion/values.yaml
> -    type: LoadBalancer
This requires an unfortunate splitting of our values.yaml config.  I've added an ingress-enabled-values.yaml that changes service types and enables the ingresses, but this will force anyone wishing to enable currently-disabled services, like deid and cohort, to manipulate the ingress-enabled-values.yaml since there is no support for doubly-inherited values.yaml files.

2021-02-22 22:46 UTC, ibmatc commented on clinical-ingestion/helm-charts/alvearie-ingestion/README.md
> +helm install ingestion . --set global.ingress.enabled=true,global.ingress.subdomain=<<INGRESS_SUBDOMAIN>>
I believe I have re-worked the Readme to accommodate your concerns.  The default instructions are as before, with an optional path to deploy using Ingresses.  I added a comment to the de-identification piece that addresses the need to merge the values from deidentification.yaml and ingress-enabled-values.yaml.

2021-02-23 16:56 UTC, luisgarcc requested changes
Nice work! Thanks for addressing the previous comments. 
I have additional comments that I think we'll want to discuss (i.e. global, nginx annotations) so marking as changes needed for now.

2021-02-23 16:56 UTC, luisgarcc commented on clinical-ingestion/helm-charts/alvearie-ingestion/README.md
> +The hostname for each service will be auto-generated based on the ingress subdomain provided.  In IBM Cloud, the ingress subdomain for your cluster can be retrieved using:
I think it would be good to a create github issue to document the instructions to do this on AWS, Google Cloud, and Azure too.

2021-02-23 16:56 UTC, luisgarcc commented on clinical-ingestion/helm-charts/alvearie-ingestion/README.md
> +helm install ingestion . -f ingress-enabled-values.yaml
I feel like we need to make this part of our test cases, @rguderian do you have plans to include the ingress path into your automated suite?

2021-02-23 16:56 UTC, luisgarcc commented on clinical-ingestion/helm-charts/alvearie-ingestion/README.md
> +Note: In order to install De-Identification in an ingress-enabled environment, you need to manually merge the values from the two previous yaml files into one joint configuration.
Good idea to update this too. I think we can omit the part about merging it "manually" and we can say that they can pass in the two files to the installation since helm supports that (I just googled this I didn't test it, but I think it should work), i.e. something like this:

`helm install  ingestion . -f de-id-pattern-values.yaml -f ingress-enabled-values.yaml`

2021-02-23 16:56 UTC, luisgarcc commented on clinical-ingestion/helm-charts/alvearie-ingestion/templates/NOTES.txt
> +{{- if not .Values.global.ingress.enabled }}
> 
> I used the convention recommended here: https://helm.sh/docs/chart_template_guide/subcharts_and_globals/
> 
> This uses "global" as a keyword, but implies it is also required for other subcharts to access them. In this case (now) it's not subcharts accessing it, but I think keeping the global keyword is important/correct.

For some reason github didn't let me reply to our existing conversation on this topic, so continuing here...

`global` values are special values that are meant to be accessed by both the parent and the subcharts. They additionally require that they are declared as such in a specific section of the `Chart.yaml`.

In this case the `ingress` configuration is specific to the parent chart, and all subcharts do not see it. If we left these decoupled, we could conceivably have support for an ingress configuration say for FHIR and have that be completely different and independent than the parent chart's ingress.

I think unless the implementation is such that the values is truly a global value, you should remove the qualifier because it does not match the definition of what globals are per the documentation.

![image](https://user-images.githubusercontent.com/1807320/108873593-84f4cc80-75b8-11eb-8969-f5e2a4297b8e.png)

2021-02-23 16:56 UTC, luisgarcc commented on clinical-ingestion/helm-charts/alvearie-ingestion/templates/NOTES.txt
> +  export FHIR_IP=$(kubectl get svc --namespace {{ .Release.Namespace }} {{ .Release.Name }}-fhir -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
I think we should update the documentation with an if/then here to get the right FHIR_IP based on whether ingress are enabled. Not sure what happens with this command currently when deploying with ingress.

2021-02-23 16:56 UTC, luisgarcc commented on clinical-ingestion/helm-charts/alvearie-ingestion/values.yaml
> +    restPort: 7001
I wouldn't call it `restPort` because what gets exposed at that port isn't really a REST API, but I can't think of a good nice short name, 'httpInputPort`, `inputPort`, `ingestionPort`, something like that just to be more accurate.

2021-02-23 16:56 UTC, luisgarcc commented on clinical-ingestion/helm-charts/alvearie-ingestion/templates/cohort_ingress.yaml
> +    kubernetes.io/ingress.class: public-iks-k8s-nginx
@ibmatc FYI

2021-02-23 16:56 UTC, luisgarcc commented on clinical-ingestion/helm-charts/alvearie-ingestion/templates/deid_ingress.yaml
> +apiVersion: extensions/v1beta1
@ibmatc FYI

2021-02-23 16:56 UTC, luisgarcc commented on clinical-ingestion/helm-charts/alvearie-ingestion/templates/kafka_ingress.yaml
> +    ingress.kubernetes.io/proxy-read-timeout: '90'
> It was a property in the sample ingress given to me by Jessmon. It controls how long it will wait on the upstream server before timing out. I'm not sure it's strictly required, but I think it's good practice to leave.

I think you should double-check with Jessmon since I don't think this property is correct. All annotations supported by the IBM Cloud Ingress implementation are the nginx annotations per the docs [here](https://cloud.ibm.com/docs/containers?topic=containers-comm-ingress-annotations#custom-connect-and-read-timeouts) or maybe I just didn't find this particular one, but that is what it seems. So I think at least the annotation name is wrong.

But I also wonder if we even need it. I don't think we do since the [default timeout is 60](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_read_timeout) so I am not sure this is giving us much different than the default and I rather us not guess randomly and just go with the default and adjust if needed.

Finally, I wonder if other clouds have other annotations from using different ingress controllers and having this here makes the ingress file incompatible with those for the future.

2021-02-23 21:45 UTC, ibmatc commented on clinical-ingestion/helm-charts/alvearie-ingestion/README.md
> +The hostname for each service will be auto-generated based on the ingress subdomain provided.  In IBM Cloud, the ingress subdomain for your cluster can be retrieved using:
Issue created: https://github.com/Alvearie/health-patterns/issues/91

2021-02-23 21:53 UTC, ibmatc commented on clinical-ingestion/helm-charts/alvearie-ingestion/README.md
> +Note: In order to install De-Identification in an ingress-enabled environment, you need to manually merge the values from the two previous yaml files into one joint configuration.
Ah, I wasn't aware of that. Good to know. I just tested it and you're right.  I'll update the readme.

2021-02-23 22:31 UTC, ibmatc commented on clinical-ingestion/helm-charts/alvearie-ingestion/templates/NOTES.txt
> +{{- if not .Values.global.ingress.enabled }}
I will change it. The way things are now configured, I concede that the "global" naming is excessive.  I had hoped to let the ingress subdomain be exposed globally so subcharts could pick it up rather than having to configure it individually, but that didn't pan out.

2021-02-23 22:33 UTC, ibmatc commented on clinical-ingestion/helm-charts/alvearie-ingestion/README.md
> +helm install ingestion . -f ingress-enabled-values.yaml
Created https://github.com/Alvearie/health-patterns/issues/92 to track this.

2021-02-23 22:37 UTC, ibmatc commented on clinical-ingestion/helm-charts/alvearie-ingestion/templates/NOTES.txt
> +  export FHIR_IP=$(kubectl get svc --namespace {{ .Release.Namespace }} {{ .Release.Name }}-fhir -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
When the Ingress is enabled (using the ingress-enabled-values.yaml) I disable all LoadBalancers.  Given this, I am skipping this entire section in the NOTES.txt file, and showing the URL to each service as part of the previous list of services.  I don't think there's any need to if/then this. Unless I'm missing something?

2021-02-23 22:39 UTC, ibmatc commented on clinical-ingestion/helm-charts/alvearie-ingestion/values.yaml
> +    restPort: 7001
Fair - changed to "httpInputPort"

2021-02-23 23:09 UTC, ibmatc commented on clinical-ingestion/helm-charts/alvearie-ingestion/templates/kafka_ingress.yaml
> +    ingress.kubernetes.io/proxy-read-timeout: '90'
I have removed the timeout from all ingress files.  It was a hold-over from the example I used to develop this and I don't believe it's necessary at this time.

The ingress.class is required in order for the ingress to work. Leaving as-is for now, but as we look into getting Ingresses to work on other clouds this will need to be reviewed.

2021-02-23 23:27 UTC, luisgarcc commented on clinical-ingestion/helm-charts/alvearie-ingestion/templates/NOTES.txt
> +  export FHIR_IP=$(kubectl get svc --namespace {{ .Release.Namespace }} {{ .Release.Name }}-fhir -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
Yeah no my point was just that we showed something analogous to what we show now in terms of how to access the exposed services outside the cluster. If that is already there, that is good, thanks!

2021-02-23 23:29 UTC, luisgarcc approved these changes
Thank you for addressing the comments! 
Cool work here 👍

2021-02-24 03:22 UTC, merged