Initial set of Charts to deploy the Alvearie Clinical Ingestion Pattern
Alvearie/health-patterns pull request #9
Opened 2020-11-17 00:20 UTC by luisgarcc

This commit includes an initial set of charts to deploy the Alvearie
Clinical Ingestion pattern.

There is a main chart that deploys the whole framework (including its
components) and an extra couple of charts used to deploy IBM FHIR and a
NiFi Registry backed by a Github repository.

The Alvearie Clinical Ingestion pattern chart deploys the following
related services:

- IBM FHIR: A FHIR server to store medical data
- Kafka: For clinical ingestion messaging
- NiFi: To deploy the ingestion flows
- NiFi Registry: To deliver the ingestion flows to be used in NiFi
- Zookeeper: Dependency needed by Kafka & NiFi

The corresponding documentation with instructions is included.

2020-11-17 12:38 UTC, ewill00 requested changes
README for nifi-registry and fhir both have copy/paste references 
nifi-registry has:
Install the helm chart with a release name `fhir`:
and 
To uninstall/delete the `ingestion` deployment:

fhir just has the reference to 'ingestion' in the uninstall text

2020-11-17 14:18 UTC, luisgarcc commented
> 
> 
> README for nifi-registry and fhir both have copy/paste references
> nifi-registry has:
> Install the helm chart with a release name `fhir`:
> and
> To uninstall/delete the `ingestion` deployment:
> 
> fhir just has the reference to 'ingestion' in the uninstall text

Good catch, fixed both - thanks!

2020-11-17 19:56 UTC, ibmatc approved these changes
Overall looks great, most of my comments are nits or questions.  A few important comments though.

Two comments I can't add in-line:

1) What are the tgz files? Are they static versions of fhir/kafka/nifi/nifi-registry/zookeeper that will need upkeep? Is there any way to pull them on-demand instead of ship them? 

2) The last image (nifi-import-latest.png) ideally should be updated to show the official Registry/Bucket/Flow Name, once those exist. (This is my concern with relying on screen caps)

2020-11-17 19:56 UTC, ibmatc commented on clinical-ingestion/helm-charts/README.md
> +2. Select _Import..._
Maybe add a comment that sometimes this takes a minute or two after the install for the registry to show up in Nifi, so "import" may not be immediately available?

2020-11-17 19:56 UTC, ibmatc commented on clinical-ingestion/helm-charts/README.md
> +That's it!
We need to either link back to the Clinical Ingestion readme or mention here all of the details about setting up the Parameter Contexts and enabling Controller Services.

2020-11-17 19:56 UTC, ibmatc commented on clinical-ingestion/helm-charts/alvearie-ingestion/.helmignore
> +# Patterns to ignore when building packages.
Curious about why "alvearie-ingestion" instead of "clinical-ingestion" for the folder name... including alvearie in the name at this level seems wrong.

2020-11-17 19:56 UTC, ibmatc commented on clinical-ingestion/helm-charts/alvearie-ingestion/README.md
> +Deletion of charts doesn't cascade to deleting associated `PersistedVolume`s and `PersistedVolumeClains`s.
The formatting of this with the trailing "s" is weird... Any reason to not include the "s" inside the code block?

2020-11-17 19:56 UTC, ibmatc commented on clinical-ingestion/helm-charts/alvearie-ingestion/README.md
> +## Contributing
Are we planning to include the contributing/license at the bottom of every readme? Or does it belong on the project's readme and that covers all sub-readmes? Just asking for consistency

2020-11-17 19:56 UTC, ibmatc commented on clinical-ingestion/helm-charts/fhir/README.md
> +kubectl exec <pod-id> -c fhir-server -- cat server.xml | grep "user name"
Maybe add a little detail about this command - is "fhir-server" a choice or does it have to be this name? what is "user name"? Is that a literal to search for "user name" from server.xml or are you supposed to replace that with your user name?

2020-11-17 19:56 UTC, ibmatc commented on clinical-ingestion/helm-charts/fhir/templates/NOTES.txt
> +1. Get the application URL by running these commands:
What is the purpose of this file? Should it be delivered, or is it notes for your development?

2020-11-17 19:56 UTC, ibmatc commented on clinical-ingestion/helm-charts/fhir/values.yaml
> +  repository: luisgarc/my-fhir
Should we move this image to an ibm/alvearie repo, instead of yours?

2020-11-17 19:56 UTC, ibmatc commented on clinical-ingestion/helm-charts/fhir/values.yaml
> +    repository: luisgarc/fhir-proxy
Same comment about luisgarc repo

2020-11-17 19:56 UTC, ibmatc commented on clinical-ingestion/helm-charts/nifi-registry/README.md
> +cd clinical-ingestion/nifi-registry
wrong directory - should be "cd clinical-ingestino/helm-charts/nifi-registry"

2020-11-17 19:56 UTC, ibmatc commented on clinical-ingestion/helm-charts/nifi-registry/README.md
> +| `git.repository`          | The repository to use to initialize the GithubPersistenceFlowProvider                                         | (The alvearie releae NiFi flow repo)   |
It would be nice for a future release to allow passing in user/token/branch tags since these charts make it really nice/easy to deploy a registry.

2020-11-17 19:56 UTC, ibmatc commented on clinical-ingestion/helm-charts/nifi-registry/templates/NOTES.txt
> +1. Get the application URLs by running these commands:
Again - should the notes be delivered?

2020-11-17 19:56 UTC, ibmatc commented on clinical-ingestion/helm-charts/nifi-registry/values.yaml
> +  repository: https://github.com/luisgarcc/nifi-flows.git
Update with https://github.com/Alvearie/health-patterns-nifi-flows now that we have that repo.

2020-11-17 20:17 UTC, luisgarcc commented
> 
> 
> Overall looks great, most of my comments are nits or questions. A few important comments though.
> 

Thanks..

> Two comments I can't add in-line:
> 
>     1. What are the tgz files? Are they static versions of fhir/kafka/nifi/nifi-registry/zookeeper that will need upkeep? Is there any way to pull them on-demand instead of ship them?
> 

Those are the chart's dependencies, some exist in external chart repositories, but the ones we created here don't yet, so I am including _all_ here in an effort to save that download step. We could eventually push our charts to some repo and have them all be downloaded, but I don't see us changing them too often, so maybe we could continue including them.

>     2. The last image (nifi-import-latest.png) ideally should be updated to show the official Registry/Bucket/Flow Name, once those exist. (This is my concern with relying on screen caps)

Yeah, I actually have that in my TODOs for once we have that out there. I added that pic there temporarily to give a feeling for what it would look like. I think once you push the flows out there and we screenshot the right bucket/flow names (and with the wording select the latest version) I don't see that changing very often, hence the concern for using screen caps should be minimized, and I think it provides good value.

2020-11-17 20:22 UTC, luisgarcc commented on clinical-ingestion/helm-charts/README.md
> +2. Select _Import..._
done

2020-11-17 20:24 UTC, luisgarcc commented on clinical-ingestion/helm-charts/README.md
> +That's it!
That is supposed to be the purpose of the next sentence:

_You should be ready to should be read to exercise the operations described in the [Running a FHIR bundle through the Clinical Ingestion Flow](https://github.com/Alvearie/health-patterns/tree/initial-charts/clinical-ingestion#running-a-fhir-bundle-through-the-clinical-ingestion-flow)._

2020-11-17 20:31 UTC, luisgarcc commented on clinical-ingestion/helm-charts/alvearie-ingestion/.helmignore
> +# Patterns to ignore when building packages.
The folder name conventionally matches the chart name and I wanted the chart to include the project name. 
Example of other charts are: nifi, nifi-registry, zookeeper, kafka 
Something generic such as "clinical-ingestion" did not seem right, it's as is the charts mentioned above would have been called: integration, integration-registry, service-coordination, and message-queue.

2020-11-17 20:32 UTC, ibmatc commented on clinical-ingestion/helm-charts/README.md
> +That's it!
Ok, but the piece I'm talking about comes before the "Running..." section. It's at the end of the prior section, "Clinical Ingestion Flow"

2020-11-17 20:37 UTC, luisgarcc commented on clinical-ingestion/helm-charts/alvearie-ingestion/README.md
> +Deletion of charts doesn't cascade to deleting associated `PersistedVolume`s and `PersistedVolumeClains`s.
You typically only include the name of the artifact, in this case `PersistedVolume` (without the `s`)
It's like in this [JavaDoc](https://docs.oracle.com/javase/8/docs/api/javax/swing/JCheckBox.html) notice in the second paragraph the `Action` class name is the only thing that is marked as `code` and as a hyhperlink, and the `s` is left out there too.

2020-11-17 20:40 UTC, luisgarcc commented on clinical-ingestion/helm-charts/alvearie-ingestion/README.md
> +## Contributing
I can go either way on this, but I don't see it on the top level parent so I added them here to the individual projects: https://github.com/Alvearie/health-patterns

I do have a preference, since each of these subdirectories are their own beasts (charts, flows, nars, etc.) and theoretically have their own set of interested parties who may contribute to one but not other, I feel it makes sense to have them in all top levels subprojects.

2020-11-17 20:49 UTC, luisgarcc commented on clinical-ingestion/helm-charts/fhir/README.md
> +kubectl exec <pod-id> -c fhir-server -- cat server.xml | grep "user name"
Honestly I don't think that is necessary, especially if you are following the instructions. If you are deviating from the instructions and providing your own names, namespaces, config, etc. you probably don't need those clarifications anyway.

2020-11-17 20:50 UTC, luisgarcc commented on clinical-ingestion/helm-charts/fhir/templates/NOTES.txt
> +1. Get the application URL by running these commands:
No, it's a really cool Helm feature that prints access mechanisms to your deployed services to the console when you deploy the chart.

2020-11-17 20:50 UTC, luisgarcc commented on clinical-ingestion/helm-charts/fhir/values.yaml
> +  repository: luisgarc/my-fhir
Yup, I think that is part of what we should eventually do in s7, not just that but in fact use the official docker fhir image from the ibm fhir team

2020-11-17 20:50 UTC, luisgarcc commented on clinical-ingestion/helm-charts/fhir/values.yaml
> +    repository: luisgarc/fhir-proxy
same response

2020-11-17 20:51 UTC, luisgarcc commented on clinical-ingestion/helm-charts/nifi-registry/README.md
> +cd clinical-ingestion/nifi-registry
good catch thanks!

2020-11-17 20:52 UTC, luisgarcc commented on clinical-ingestion/helm-charts/nifi-registry/README.md
> +| `git.repository`          | The repository to use to initialize the GithubPersistenceFlowProvider                                         | (The alvearie releae NiFi flow repo)   |
agree - have it in my TODOs

2020-11-17 20:53 UTC, luisgarcc commented on clinical-ingestion/helm-charts/nifi-registry/templates/NOTES.txt
> +1. Get the application URLs by running these commands:
yes

2020-11-17 20:53 UTC, luisgarcc commented on clinical-ingestion/helm-charts/nifi-registry/values.yaml
> +  repository: https://github.com/luisgarcc/nifi-flows.git
done

2020-11-17 21:01 UTC, luisgarcc commented on clinical-ingestion/helm-charts/README.md
> +That's it!
k, see the latest updates

2020-11-17 21:20 UTC, ewill00 approved these changes

2020-11-17 21:28 UTC, ibmatc commented on clinical-ingestion/helm-charts/alvearie-ingestion/README.md
> +Deletion of charts doesn't cascade to deleting associated `PersistedVolume`s and `PersistedVolumeClains`s.
I understand the reasoning, and in javadoc its that way partially so it can link to the corresponding type... In this case it's just a markup of some text... Not sure the purity of marking up just the exact type (vs the plural name) outweighs the strange formatting of the trailing 's'.  Not a big deal, just looks odd.

2020-11-17 21:29 UTC, ibmatc commented on clinical-ingestion/helm-charts/alvearie-ingestion/README.md
> +## Contributing
That's reasonable.  I was just curious what our expectation/convention was so I could be consistent.

2020-11-17 22:59 UTC, ibmatc commented on clinical-ingestion/helm-charts/fhir/README.md
> +kubectl exec <pod-id> -c fhir-server -- cat server.xml | grep "user name"
My point is that this is the readme, but I don't understand if this command is intended to be run exactly as-is, or if the "user name" is intended to be replaced by a user-specified value "atclark" vs "user name".  Same with fhir-server. Is that just a recommended name, or does it HAVE to be that value in order for other pieces to work correctly? It's just not clear what, if any, is variable.

2020-11-17 23:23 UTC, ranum approved these changes
Looks good to me

2020-11-18 15:53 UTC, luisgarcc commented on clinical-ingestion/helm-charts/fhir/README.md
> +kubectl exec <pod-id> -c fhir-server -- cat server.xml | grep "user name"
ok, modified the command and added a clarification, it should much less ambiguous now

2020-11-18 15:54 UTC, merged